export const hardforks = [
  ['chainstart', require('./chainstart.json')],
  ['homestead', require('./homestead.json')],
  ['dao', require('./dao.json')],
  ['tangerineWhistle', require('./tangerineWhistle.json')],
  ['spuriousDragon', require('./spuriousDragon.json')],
  ['byzantium', require('./byzantium.json')],
  ['constantinople', require('./constantinople.json')],
  ['petersburg', require('./petersburg.json')],
  ['istanbul', require('./istanbul.json')],
  ['muirGlacier', require('./muirGlacier.json')],
  ['berlin', require('./berlin.json')],
  ['london', require('./london.json')],
  ['shanghai', require('./shanghai.json')],
  ['merge', require('./merge.json')],
  ['devnet-chainstart', require('./devnet-chainstart.json')],
  ['mainnet-chainstart', require('./mainnet-chainstart.json')],
  ['testnet-chainstart', require('./testnet-chainstart.json')],
  ['testnet-hf-1', require('./testnet-hf-1.json')],
  ['mainnet-hf-1', require('./mainnet-hf-1.json')],
  ['free-staking', require('./free-staking.json')],
  ['testnet-hf-2', require('./testnet-hf-2.json')],
  ['mainnet-hf-2', require('./mainnet-hf-2.json')],
  ['devnet-hf-2', require('./devnet-hf-2.json')]
];
